# Generated by Django 5.0.3 on 2024-10-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_field', models.CharField(choices=[('st', 'study'), ('gm', 'gaming'), ('hm', 'health & madical'), ('fs', 'fasion'), ('tc', 'technology'), ('ms', 'merchendise')], default=0, max_length=2)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('item_name', models.CharField(max_length=200)),
                ('item_prize', models.CharField(max_length=50)),
                ('item_avail', models.BooleanField(default=True)),
            ],
        ),
    ]
