# Generated by Django 5.0.3 on 2024-10-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0005_user_profle_user_alter_user_profle_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profle',
        ),
    ]
