# Generated by Django 5.0.3 on 2024-11-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0007_alter_shopsy_item_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsy',
            name='item_prize',
            field=models.IntegerField(),
        ),
    ]
