# Generated by Django 5.0.3 on 2024-11-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0006_delete_user_profle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsy',
            name='item_prize',
            field=models.IntegerField(max_length=50),
        ),
    ]
