# Generated by Django 5.0.3 on 2024-12-09 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0010_rename_user_profle_profile'),
        ('mychat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunch.profile'),
        ),
    ]
