# Generated by Django 5.0.3 on 2024-10-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_follow_follower_count_follow_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
    ]
