# Generated by Django 5.0.3 on 2024-10-30 03:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_messages_user_messages_read_reciept_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='messaging',
        ),
    ]
