# Generated by Django 5.0.3 on 2024-11-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0010_rename_user_profle_profile'),
        ('social', '0006_rename_messages_messaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaging',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='bunch.profile'),
        ),
    ]
