# Generated by Django 5.0.3 on 2024-11-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0010_rename_user_profle_profile'),
        ('social', '0008_alter_messaging_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='profile_photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='bunch.profile'),
        ),
    ]
