# Generated by Django 5.0.3 on 2024-11-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_messaging_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='profile_photo',
        ),
    ]
