# Generated by Django 5.0.3 on 2024-09-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_field', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=50)),
                ('course_des', models.CharField(max_length=300)),
                ('course_release', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
