# Generated by Django 5.0.3 on 2024-09-21 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='course_field',
            field=models.CharField(choices=[('wb', 'web development'), ('Ad', 'App development'), ('ML', 'Machine learning'), ('AI', 'Artificial intelligence'), ('DS', 'Data science'), ('CS', 'Cyber security')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='cours',
            name='course_release',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
