# Generated by Django 5.0.3 on 2024-09-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0002_cours_course_image_alter_cours_course_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='course_oppos',
            field=models.TextField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='cours',
            name='course_road',
            field=models.TextField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='cours',
            name='course_salary',
            field=models.TextField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='cours',
            name='course_stack',
            field=models.TextField(default=0, max_length=500),
        ),
    ]
