# Generated by Django 5.0.3 on 2024-09-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0003_cours_course_oppos_cours_course_road_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='esehi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_varities', models.ManyToManyField(related_name='esehi', to='bunch.cours')),
            ],
        ),
    ]
