# Generated by Django 5.0.3 on 2024-09-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0004_esehi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='course_oppos',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='course_road',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='course_salary',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='course_stack',
        ),
        migrations.DeleteModel(
            name='esehi',
        ),
    ]
