# Generated by Django 5.0.3 on 2024-10-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0007_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tasks',
            new_name='user',
        ),
    ]
